# Generated by Django 2.2rc1 on 2019-03-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcarecentre',
            name='fees',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childcarecentre',
            name='infantVacancies',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childcarecentre',
            name='k2Vacancies',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
